# SPDX-FileCopyrightText: Â© 2025 Jinwoo Park (pmnxis@gmail.com)
#
# SPDX-License-Identifier: MIT

[build]
target = "index.html"
filehash = false

[watch]
ignore = ["dist", "target"]

[tools]
wasm-opt = false
